
export const cat_recipes_array = [
    {
        icon: '',
        title: 'Fast Delivery',
        weigth: '400G',
        description: '',
        price: '',
        price_cut: '',
    },
    {
        icon: '',
        title: '30 Day Return',
        weigth: '400G',
        description: '',
        price: '',
        price_cut: '',
    },
    {
        icon: '',
        title: '24/7 Support',
        weigth: '400G',
        description: '',
        price: '',
        price_cut: '',
    },
    {
        icon: '',
        title: 'Payment security',
        weigth: '400G',
        description: '',
        price: '',
        price_cut: '',
    },
    {
        icon: '',
        title: 'Fast Delivery',
        weigth: '400G',
        description: '',
        price: '',
        price_cut: '',
    },
    {
        icon: '',
        title: '30 Day Return',
        weigth: '400G',
        description: '',
        price: '',
        price_cut: '',
    },
    {
        icon: '',
        title: '24/7 Support',
        weigth: '400G',
        description: '',
        price: '',
        price_cut: '',
    },
    {
        icon: '',
        title: 'Payment security',
        weigth: '400G',
        description: '',
        price: '',
        price_cut: '',
    }
]